/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stroom.analytics.demo.eventgen;

import org.junit.Test;

public class EventGenTest {
    @Test public void testAppHasAGreeting() {


    }
}
